services:
  db:
    restart: always
    image: postgres:16-alpine
    container_name: database
    env_file: ./backend/.env.production
    environment:
      TZ: America/Santiago
      PGTZ: America/Santiago
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    env_file: ./backend/.env.production
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn api:app --host 0.0.0.0 --port 8000

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file: ./frontend/.env.production
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src

volumes:
  postgres_data:
